### PR TITLE
CLI Support

### PR DESCRIPTION
**Pull request by roborourke**
This should be enough but I'm not getting it to trigger in PHPStorm still. Could use some input from @nprasath002, I think @shadyvb got this working manually too?

EDIT: Now working! Thanks @tareiking

### CODE REVIEW

**Comment by tareiking** [comment]
@roborourke - hacked together a WIP over on https://github.com/tareiking/Xdebug/pull/1 to hopefully help.

I'm really not sure of the implications of hard-setting the IP + remove zend support, but it WFM.

Props to https://github.com/nprasath002 for the originally IP suggestion though :)

**Comment by roborourke** [comment]
@tareiking updated it thanks to that - was wondering that IP was coming from and it's the SSH Client which we can get programatically. This is working now 😁

**Comment by shadyvb** [comment]
Hmm, I took a bit different approach, as I didn't want to activate xdebug all the time, so I opted to export/forward the `XDEBUG_CONFIG` environment variable to activate/deactivate it as I needed from my host ( when I used `@local` alias ).

The PR is solid though, great work!

**Comment by tareiking** [comment]
It might actually be preferred to run xdebug in a Just In Time fashion. Yesterday PHPStorm asked me to map PHPUnit locally (indicating its running all the time), and could slow some instances down.

I'm also just happy to have this in my life. Thanks @roborourke

**Comment by roborourke** [comment]
@shadyvb yeah it's a good shout really as you def don't want XDebug on for PHPUnit test runs, at least not all the time.

Is it definitely running all the time when used via `remote_enable`? Toggling on and off via `config.yaml` wouldn't be ideal as it'd require a provision. Wonder how else we could achieve that.

**Comment by BronsonQuick** [comment]
Nice work folks! I'll test this and merge it in when I'm back on deck next week.

>Toggling on and off via config.yaml wouldn't be ideal as it'd require a provision. Wonder how else we could achieve that.

We could write a couple of scripts that run either `phpenmod xdebug` or `phpdismod xdebug`?
You'd need to `vagrant ssh` into the box to run the scripts though.

chassis__vagrantvagrant___ssh__vagrant_ssh_2018-03-01_10-28-03

Let me know what you folks think about that idea. If you're keen I will open a new issue for it.

**Comment by roborourke** [comment]
Meh, running `phpenmod` and `phpdismod` is easy enough, we can always recommend some bash aliases or a bash function for something like `vagrant ssh -c phpenmod xdebug` on the readme.

Everyone happy for this to be a-merged?

**Comment by shadyvb** [comment]
I've fiddled with the idea of passing an env var to enable/disable xdebug remote debugging on the spot, ie `XDEBUG_CONFIG="remote_enable=1" wp @local do something` , but so far I couldn't let the extension update the `config.ssh.forward_env` properly, had to update `Vagrantfile` to add it directly in there. So now fiddling with allowing some `config.ssh` options to be set from `config.yaml`, WIP so far, and quite slow given my relatively ignorance of ruby.

**Pull request merged**
